kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-admin
secrets:
  - name: airflow-admin-dockercfg-jlf4r
imagePullSecrets:
  - name: airflow-admin-dockercfg-jlf4r
automountServiceAccountToken: true