apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: airflow-scheduler
  namespace: a1b9b0-dev
spec:
  scaleTargetRef:
    kind: Deployment
    name: dev-release-af-airflow-scheduler
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

