kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-admin-binding
subjects:
  - kind: ServiceAccount
    name: airflow-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow